LMS-demo/force-app/main/default/objects/Merchandise__c/Merchandise__c.object-meta.xml
<CustomObject>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandises</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

LMS-demo/force-app/main/default/objects/Merchandise__c/fields/Merchandise_Desc__c.field-meta.xml
<CustomField>
    <fullName>Merchandise_Desc__c</fullName>
    <label>Merchandise Desc</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

LMS-demo/force-app/main/default/objects/Merchandise__c/fields/Merchandise_Stock__c.field-meta.xml
<CustomField>
    <fullName>Merchandise_Stock__c</fullName>
    <label>Merchandise Stock</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

LMS-demo/force-app/main/default/classes/UpsertClass.cls
@isTest
public class UpsertClass {
    public static testmethod void main(){
        List<Merchandise__c> obj = new List<Merchandise__c>();
        obj = [SELECT merchandise_stock__c FROM merchandise__c];
        for(Merchandise__c m: obj){
            m.Merchandise_Stock__c += 1000;
        }
        
        Merchandise__c obj1 = new Merchandise__c();
        obj1.name = 'Upsert Test';
        obj1.merchandise_desc__c = 'agppihsa sdh sdh sh ';
        obj1.Merchandise__c = 1123;
        obj1.Merchandise_Stock__c = 1400;
        
        obj.add(obj1);
        
        UPSERT obj;
    }
}