LMS-demo/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>1{000}</displayFormat>
        <label>Employee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LMS-demo/force-app/main/default/objects/Employee__c/fields/deptno__c.field-meta.xml
<CustomField>
    <fullName>deptno__c</fullName>
    <label>Employee Deptno</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

LMS-demo/force-app/main/default/objects/Employee__c/fields/ename__c.field-meta.xml
<CustomField>
    <fullName>ename__c</fullName>
    <label>Employee Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

LMS-demo/force-app/main/default/objects/Employee__c/fields/job__c.field-meta.xml
<CustomField>
    <fullName>job__c</fullName>
    <label>Employee Designation</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

LMS-demo/force-app/main/default/objects/Employee__c/fields/salary__c.field-meta.xml
<CustomField>
    <fullName>salary__c</fullName>
    <label>Employee Salary</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

LMS-demo/force-app/main/default/classes/insert_cc_class.cls
public with sharing class insert_cc_class {

    public String job { get; set; }

    public String deptno { get; set; }

    public String esalary { get; set; }

    public String ename { get; set; }

    public PageReference cancel() {
        return null;
    }


    public PageReference insertRecord() {
        Employee__c obj = new Employee__c();
        obj.ename__c = ename;
        obj.salary__c = esalary;
        obj.deptno__c = deptno;
        obj.job__c = job;
        INSERT obj;
        PageReference pr = new PageReference('https://training78-dev-ed.develop.my.salesforce.com/a05/o');
//        return null;
        return pr;
    }

}