LMS-demo/force-app/main/default/objects/Hero_Employee__c/Hero_Employee__c.object-meta.xml
<CustomObject>
    <label>Hero Employee</label>
    <nameField>
        <label>Hero Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hero Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LMS-demo/force-app/main/default/objects/Hero_Employee__c/fields/empAddr__c.field-meta.xml
<CustomField>
    <fullName>empAddr__c</fullName>
    <label>Employee Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

LMS-demo/force-app/main/default/objects/Hero_Employee__c/fields/empDept__c.field-meta.xml
<CustomField>
    <fullName>empDept__c</fullName>
    <label>Employee Dept</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

LMS-demo/force-app/main/default/objects/Hero_Employee__c/fields/empFName__c.field-meta.xml
<CustomField>
    <fullName>empFName__c</fullName>
    <label>Employee Father&apos;s name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

LMS-demo/force-app/main/default/objects/Hero_Employee__c/fields/empSalary__c.field-meta.xml
<CustomField>
    <fullName>empSalary__c</fullName>
    <label>Employee Salary</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

LMS-demo/force-app/main/default/classes/EmployeeInfo.cls
public class EmployeeInfo {
	@auraEnabled
    public static void insertEmp(string eName, string eFname, string eAddr, string eDept, string eSal) {
        Hero_Employee__c hemp = new Hero_Employee__c();
        try{
            hemp.name = eName;
            hemp.empFName__c = eFname;
            hemp.empAddr__c = eAddr;
            hemp.empDept__c = eDept;
            hemp.empSalary__c = Integer.valueOf(eSal);
        }
        catch (Exception e){
            system.debug(e);
        }
        Insert hemp;
    }
}